controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    heuristic_controller:
      type: heuristic_controller/HeuristicController

heuristic_controller:
  ros__parameters:
    gait_frequency: 1.0 #0.00001
    # swing_durations: [0.3, 0.3, 0.3, 0.3]

    body_height: 0.15

    swing_joint_kp: 7.5
    swing_joint_kd: 0.5

    stance_joint_kp: 0.0
    stance_joint_kd: 0.05

    balancing_force_kp: 1000.0
    balancing_force_kd: 10.0
    balancing_torque_kp: 50.0
    balancing_torque_kd: 50.0

    mass: 0.0
    min_normal_force: 1.0
    max_normal_force: 50.0
    friction_coefficient: 0.5

    stand_controller_max_body_vel: 10000.0 #0.1 #10000.0
    stand_controller_max_body_angvel: 9999.0

    body_pos_smoothing: 1.0
    body_vel_smoothing: 1.0