controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    heuristic_controller:
      type: heuristic_controller/HeuristicController

heuristic_controller:
  ros__parameters:
    gait_frequency: 1.0

    swing_joint_kp: 0.5
    swing_joint_kd: 0.05

    balancing_force_kp: 0.1
    balancing_force_kd: 0.0
    balancing_torque_kp: 0.0
    balancing_torque_kd: 0.0
